### ISSUE TITLE
Add gitter hook to circleci config 

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#60]
**Is your feature request related to a problem? Please describe.**
QoL/Enhancement/laziness. 

**Describe the solution you'd like**
Have circleci ping out to gitter so we get notifications for failed builds.

**Describe alternatives you've considered**
Not being lazy.. I guess. :) 

**Additional context**
gitter says do this:
```
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: YOUR_WEBHOOK_URL
```
